-- AlterTable
ALTER TABLE "ProgressionStrategySimpleOpts" ADD COLUMN     "lossCountMax" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN     "lossCountStep" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "lossMaxSets" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "lossWeightDelta" DOUBLE PRECISION NOT NULL DEFAULT 1.25,
ADD COLUMN     "massWeightDelta" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN     "strengthWeightDelta" DOUBLE PRECISION NOT NULL DEFAULT 5;
